### PR TITLE
Discussing piracy & offline-mode is no longer allowed

### PR DESCRIPTION
**Pull request by aurorasmiles**
Piracy is not allowed by the Discord ToS.
While offline-mode does not necessarily mean piracy, in most of the cases we encouter it in paper-help it is used to allow unlicensed players to join.
I hope to get some honest feedback on this, especially if the wording is understandable and somewhat clear

### CODE REVIEW

**Review by Proximyst — APPROVED** [review]

**Comment by simpleauthority** [comment]
Seems good to me. However, it may be good to also continue to include that it's not okay to harass them about it. Just deny support and move on. But that might be covered by "don't be a jerk" so maybe it's fine.

But this is good because there are legitimate use cases.

**Comment by aurorasmiles** [comment]
> But that might be covered by "don't be a jerk" so maybe it's fine.
It is^^

**Comment by simpleauthority** [comment]
Then sounds great

**Comment by Felenov** [comment]
That makes sense. The game is cheap enough and now there is really no excuse to not buy it.

**Comment by kennytv** [comment]
> That makes sense. The game is cheap enough and now there is really no excuse to not buy it.

Not quite true, see https://twitter.com/BobicraftMC/status/1460666425568333835 and the quoted Tweet with replies

**Comment by electronicboy** [comment]
Not really relevant, this has been a community stance for years and this is just carving it into stone as something that can be pointed to more formally

**Comment by lukeeey** [comment]
disagreed. offline mode is not piracy. ban discussing piracy, not this.

**Comment by Chew** [comment]
Yeah, this wasn't clarified in the PR title very well.

Bringing over my 2 cents:

> We're doing 2 things here:
> Explicitly Banning piracy (was already banned by Discord)
> Dropping (official) support for offline mode

As stated, we still support legitimate means of offline mode, offline mode being enabled for various reasons:
- Bungeecord/Velocity (proxies) - Acceptable due to their nature. This is assuming bungeecord is set to true
- Allowing non-Mojang users to join (this is what we're disallowing)

While Offline mode doesn't necessarily imply pirating, it does enable it, so we're banning non-legitimate reasons for it.

**Comment by simpleauthority** [comment]
The ability for players to buy the game is not and should not be Paper's responsibility. Server owners who try to guilt-trip the community into supporting them due to economic issues preventing their players from buying the game also should not be Paper's responsibility. It's already not allowed by Discord, and in order to support that mode would require a separate support channel and extra effort on the team's behalf and also from the community of helpers and it's just infeasible. As much as I know about economic inequality (both related and not related to Minecraft), it's not even about that from this side of things. There's just not enough interest or ability to support that from the server software side of things. There are other avenues of support that they can go to anyway. 🤷‍♂️

Whether or not the game is affordable or what Mojang will do to make it affordable based on geographic region should not be Paper's problem.

**Comment by Logics4** [comment]
So, from what I understand overall, this is about not letting further discussion happening at all, compared to the previous stance, where the team members would deny support (and rightfully so) but if someone else decided they want to help, they could do it? Would someone foreign to the team who is willing to help not be allowed to anymore?

> There have been plenty of cases in #paper-help where a user is asking for help for issues that can only occur when having online-mode set to false.

This makes sense. However, remember that there has also been at least one case where a patch broke offline-mode - I recall this issue in 2018 where a freshly made commit would make the server try to fetch player skins in offline-mode, even though it should not fetch any skins at all. It got fixed soon after, though, but my point is that "not supporting offline-mode" should not also mean "conveniently break essential server behavior". Would bug reports for such cases still be accepted?

**Comment by electronicboy** [comment]
These are guidelines, not hard enforced rules, nothing is changing here bar formalising a general community stance towards stuff in a manner that can be pointed to.
offline mode in regards to issue reports is subjective, if it's something we've introduced, generally we'll fix it, but, offline mode is not a priority to us.

**Comment by aurorasmiles** [comment]
I'd love to get some more feedback & opinions especially regarding the general wording

**Comment by masterX244** [comment]
How is the case handled when a bug reproduction of something needs multiple players for it to happen?

**Comment by aurorasmiles** [comment]
If only used for testing and the bug itself is not caused by using offline-mode then that would be no problem

**Comment by dawon** [comment]
Just maybe another point of view, in my opinion bit extreme, but I saw this on one discord for some plugins.

Their policy is offline-mode only for proxies with online mode turned on on the proxy. When you ask for support and they detect (from the logs ususally) you use offline-mode, they will give you "Do Not Support" role. If you promise then you will not use offline-mode, they will remove it, but upon second infraction it will either be permanent or they will ban you.

I am not sure how strictly are they enforcing these rules for multi user testing, but I saw, that they recommend buying multiple accounts for these cases.

**Comment by Proximyst** [comment]
> Just maybe another point of view, in my opinion bit extreme (in regard to testing multiuser stuff), but I saw this on one discord for some plugins.
> 
> Their policy is offline-mode only for proxies with online mode turned on on the proxy. When you ask for support and they detect (from the logs ususally) you use offline-mode, they will give you "Do Not Support" role. If you promise then you will not use offline-mode, they will remove it, but upon second infraction it will either be permanent or they will ban you.
> 
> I am not sure how strictly are they enforcing these rules for multi user testing, but I saw, that they recommend buying multiple accounts for these cases.

The moderation team has no intentions of adding roles or otherwise marking offline-mode users. For testing purposes (e.g. with development), it is absolutely acceptable to use offline-mode. These rules would more matter to those who come to `#paper-help` asking for help with their production servers that are offline-mode without the proxy modes being enabled, as well as those arguing for their need for it. As such, anyone making a plugin or the likes asking for help while using offline-mode will still get support (assuming it isn't _because_ of offline-mode that it broke, such as in the case of Mojang API requests).

**Comment by dawon** [comment]
> The moderation team has no intentions of adding roles or otherwise marking offline-mode users. For testing purposes (e.g. with development), it is absolutely acceptable to use offline-mode. These rules would more matter to those who come to `#paper-help` asking for help with their production servers that are offline-mode without the proxy modes being enabled, as well as those arguing for their need for it. As such, anyone making a plugin or the likes asking for help while using offline-mode will still get support (assuming it isn't _because_ of offline-mode that it broke, such as in the case of Mojang API requests).

Yes and I fully agree with that, just wanted to point out that even more extreme measures do exist. I guess Paper's approach is ideal in this matter. :)

BTW another valid use-case though rare nowadays (and I guess the original intention for offline-mode) is when people just want to play on LAN without internet...

**Review by kennytv — APPROVED** [review]

**Review by MiniDigger — APPROVED** [review]

**Pull request merged**
