### PR TITLE
Persist quiz completion

### PR DESCRIPTION
**Pull request by clrxbl**
Prevents the quiz from showing up if it has been completed once

### CODE REVIEW

**Comment by Smart123s** [comment]
What about [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage)? It's similar to cookies, but it's contents are not sent with every request sent to the site.

But that only matter if the maintainers will ever take a look at this. 🙃

**Comment by MiniDigger** [comment]
I would prefer localStorage

**Comment by MiniDigger** [comment]
do it michael! now!

**Comment by clrxbl** [comment]
thank you github copilot very cool

**Comment by MiniDigger** [comment]
this would have a time out (aka be asked every month or something) but good enough for now, thanks

**Pull request merged**
