### PR TITLE
Fix typo + remove extra 'also' on sponsors page

### PR DESCRIPTION
**Pull request by TwoLeggedCat**

### CODE REVIEW

**Comment by MiniDigger** [comment]
whats wrong with that also? its a second option that goes towards the same pod, so I think that sentence makes sense?

**Comment by TwoLeggedCat** [comment]
> whats wrong with that also? its a second option that goes towards the same pod, so I think that sentence makes sense?

Well, given the sentence starts with “additionally,” “also” seems rather unnecessary, and it’s also used again a couple words later which makes the sentence a bit awkward imho.

Doesn’t really matter tho, just removed that while I was in there for the typo

**Comment by Bobcat00** [comment]
> Well, given the sentence starts with “additionally,” “also” seems rather unnecessary, and it’s also used again a couple words later which makes the sentence a bit awkward imho.

Additionally, I also agree with TwoLeggedCat, also, too.   :-)

**Review by Proximyst — APPROVED** [review]
I agree that this reads better.

**Pull request merged**
