### PR TITLE
Add dropdown to Community link

### PR DESCRIPTION
**Pull request by simpleauthority**
Screenshot+2019-06-03+02 36 46

Add dropdown to Community link for quick access to forums/discord/other community options.

This could be potentially redesigned to be more aesthetically pleasing, but in terms of ease-of-access of the forum, this will save a lot of time for users.

Having to click community and then click forums is a long way to go for frequent users who don't have bookmarks (me).

### CODE REVIEW

**Comment by simpleauthority** [comment]
Note, if approved, this still needs a discord invite link (at the very least) to be added for the menu to be fully functional

**Comment by zachbr** [comment]
I like the concept but I think we're going to want to figure out the styling before we merge this.

**Comment by simpleauthority** [comment]
Any thoughts on the styling? I'll see if I can style it a bit.

**Comment by Blazzike** [comment]
Yeah, nice idea. Here's how I'd like it to look:
Dropdown

**Comment by aikar** [comment]
@simpleauthority you able to update it to be like what @Blazzike showed?

**Comment by simpleauthority** [comment]
@aikar I forgot about this

Possibly yes, I'll update the PR soon

**Comment by simpleauthority** [comment]
This quite closely approximates @Blazzike's image: https://i.imgur.com/cvzzROX.png

However, there is one problem. When moving to select one of the options, the menu item loses its focus and just the menu shows. Can we use JS or something to force the menu item to stay in a hovered state? See: https://i.imgur.com/AgHaxiX.png

**Comment by simpleauthority** [comment]
Also, it doesn't appear that there is a discord icon in the [material icons list](https://material.io/resources/icons/?search=discord&style=baseline), so instead I used the phone and chat icon.

**Comment by Turbotailz** [comment]
You don't need any JS for this at all.

Put the dropdown `ul` inside the `li` and then use CSS to display it when you hover over the `li` element. Something like this:

```
ul.dropdown-menu {
  display: none;
}

li.dropdown:hover ul.dropdown-menu {
  display: block; // or flex, or whatever
}
```

Also worth noting that only `li` elements can be children of `ul` or `ol` elements, [as per the HTML spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-ul-element).

**Comment by simpleauthority** [comment]
Thanks I'll try it.

**Comment by simpleauthority** [comment]
This works. I tried what @Turbotailz mentioned, but could not figure it out with CSS. @Turbotailz, if you see something I don't please feel free to fork this PR and edit styles.scss for a pure CSS solution.

Otherwise, this if fairly minimal besides a bit of duped CSS.

Menu stays open now. Is there anything else that needs to be done @aikar?

**Pull request merged**
