### PR TITLE
move travertine to legacy page

### PR DESCRIPTION
**Pull request by simpleauthority**
As Travertine has been discontinued as announced in Discord, this PR removes it from the downloads page.

(Going along with https://github.com/PaperMC/PaperDocs/pull/63)

### CODE REVIEW

**Comment by electronicboy** [comment]
legacy

**Comment by simpleauthority** [comment]
Updated legacy page to include paper/travertine tabs. Provides links to select versions as defined in object at top of script. I had to include the version/build in the object in the script because hitting the API to find build and then hitting API again to get DL information was slow. Seems good, looks alright, and works well.

**Comment by simpleauthority** [comment]
Anything that needs to be done here in order to merge?

**Comment by MiniDigger** [comment]
> Anything that needs to be done here in order to merge?

not much :P

**Pull request merged**
