### PR TITLE
Expose SHA256 hashes, implements #121

### PR DESCRIPTION
**Pull request by MiniDigger**

### CODE REVIEW

**Comment by MiniDigger** [comment]
![https://i.imgur.com/JopIuIX.png)(https://i.imgur.com/JopIuIX.png)

**Review by aurorasmiles — APPROVED** [review]
stoopid german

**Comment by lynxplay** [comment]
Should we add these to the legacy download page as well while at it ?

**Review by kennytv — APPROVED** [review]
Pff legacy 💩

**Pull request merged**
